spring:
  application:
    name: backend-assignment
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/ipl2
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # Removed the explicit dialect specification
  data:
    redis:
      host: localhost  # Added host specification for Redis
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 9999

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.indium: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.schema: DEBUG
    org.hibernate.type.descriptor.sql: TRACE  # Added to show SQL parameter values
    com.zaxxer.hikari: DEBUG  # Added to show more details about database connection